// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"github.com/hantonelli/ghipster/product/internal/repository/entgen/product"
	"github.com/hantonelli/ghipster/product/internal/repository/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	productFields := schema.Product{}.Fields()
	_ = productFields
	// productDescName is the schema descriptor for name field.
	productDescName := productFields[1].Descriptor()
	// product.NameValidator is a validator for the "name" field. It is called by the builders before save.
	product.NameValidator = productDescName.Validators[0].(func(string) error)
}
