apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-deployment
  labels:
    app: graphql
spec:
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
      - name: graphql
        image: localhost:32000/graphql:registry
        ports:
        - containerPort: 8080
