// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: products.proto

package product

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/types"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Product) Validate() error {
	return nil
}
func (this *IDRequest) Validate() error {
	return nil
}
func (this *CreateProductRequest) Validate() error {
	return nil
}
func (this *UpdateProductRequest) Validate() error {
	return nil
}
func (this *ListProductsResponse) Validate() error {
	for _, item := range this.Products {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Products", err)
			}
		}
	}
	return nil
}
func (this *ListProductsRequestOrder) Validate() error {
	return nil
}
func (this *ListProductsRequestFilter) Validate() error {
	return nil
}
func (this *ListProductsRequest) Validate() error {
	if this.OrderBy != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.OrderBy); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("OrderBy", err)
		}
	}
	if this.Filter != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Filter); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Filter", err)
		}
	}
	return nil
}
